# Generated by Django 5.2.1 on 2025-05-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_birth_date_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STF", "Staff"),
                    ("SUP", "Support"),
                    ("RES", "Research"),
                    ("LED", "Lead"),
                    ("CMP", "Company Owner"),
                    ("OWN", "Owner"),
                ],
                default="OWN",
                max_length=3,
                verbose_name="User Role",
            ),
        ),
    ]
