services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    pull_policy: build
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: backend-db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
      POSTGRES_SSLMODE: disable
      POSTGRES_PORT: 5432
      SECRET_KEY: foo
      DOCS_USERNAME: docs
      DOCS_PASSWORD: bar
      LOG_STYLE: ${LOG_STYLE:-json}
    networks:
      - app-network
    depends_on:
      - backend-db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BEARER_TOKEN: ${REACT_APP_BEARER_TOKEN}
    container_name: frontend
    image: react-nginx:latest
    pull_policy: build
    restart: always
    environment:
      REACT_APP_BEARER_TOKEN: ${REACT_APP_BEARER_TOKEN}
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge