# Default value None added to Optional class members by fix.py
# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import datetime
import decimal
import pydantic
from typing import Optional


class Customer(pydantic.BaseModel):
    customer_id: str
    user_id: str
    name: Optional[str] = None
    company_name: Optional[str] = None
    organisation: Optional[bool] = None
    contact_person: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    address_line1: Optional[str] = None
    address_line2: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    postal_code: Optional[str] = None
    country: Optional[str] = None
    created_at: Optional[datetime.datetime] = None
    updated_at: Optional[datetime.datetime] = None
    is_deleted: bool
    deleted_at: Optional[datetime.datetime] = None


class Invoice(pydantic.BaseModel):
    invoice_id: str
    user_id: str
    job_id: str
    customer_id: str
    invoice_number: str
    invoice_date: datetime.date
    due_date: Optional[datetime.date] = None
    subtotal: decimal.Decimal
    tax_rate: Optional[decimal.Decimal] = None
    tax_amount: Optional[decimal.Decimal] = None
    total_amount: decimal.Decimal
    invoice_status: str
    payment_date: Optional[datetime.date] = None
    notes: Optional[str] = None
    created_at: Optional[datetime.datetime] = None
    updated_at: Optional[datetime.datetime] = None
    is_deleted: bool
    deleted_at: Optional[datetime.datetime] = None


class InvoiceLineItem(pydantic.BaseModel):
    line_item_id: str
    invoice_id: str
    description: str
    quantity: decimal.Decimal
    unit_price: decimal.Decimal
    total_price: decimal.Decimal
    created_at: Optional[datetime.datetime] = None
    updated_at: Optional[datetime.datetime] = None


class Job(pydantic.BaseModel):
    job_id: str
    user_id: str
    customer_id: str
    job_title: str
    job_description: Optional[str] = None
    job_status: str
    start_date: Optional[datetime.date] = None
    end_date: Optional[datetime.date] = None
    estimated_hours: Optional[decimal.Decimal] = None
    actual_hours: Optional[decimal.Decimal] = None
    daily_rate: Optional[decimal.Decimal] = None
    hourly_rate: Optional[decimal.Decimal] = None
    total_amount: Optional[decimal.Decimal] = None
    created_at: Optional[datetime.datetime] = None
    updated_at: Optional[datetime.datetime] = None
    is_deleted: bool
    deleted_at: Optional[datetime.datetime] = None


class User(pydantic.BaseModel):
    user_id: str
    sub: str
    email: str
    email_verified: Optional[bool] = None
    first_name: str
    last_name: str
    birthdate: Optional[datetime.date] = None
    created_date: datetime.datetime
    updated_at: datetime.datetime
    is_deleted: bool
    deleted_at: Optional[datetime.datetime] = None
