# Generated by Django 5.2.1 on 2025-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_company_deleted_date_company_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
