# Generated by Django 5.2.1 on 2025-06-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
