services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    pull_policy: build
    ports:
    - '8000:8000'
    environment:
      POSTGRES_HOST: backend-db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
      POSTGRES_SSLMODE: disable
      POSTGRES_PORT: 5432
      SECRET_KEY: foo
      DOCS_USERNAME: docs
      DOCS_PASSWORD: bar
      LOG_STYLE: ${LOG_STYLE:-json}

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    image: frontend:latest
    restart: always
    pull_policy: build # remove for procution rebuilds
    ports:
      - "127.0.0.1:3000:80" # Restrict to localhost
    volumes:
      - ./frontend/src:/app/src # remove for production rebuilds
      - ./frontend/public:/app/public
    depends_on:
      - backend
        # condition: service_healthy
