# Generated by Django 5.2.1 on 2025-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
