# Default value None added to Optional class members by fix.py
# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import datetime
import pydantic
from typing import Optional


class Customer(pydantic.BaseModel):
    customer_id: str
    user_id: str
    name: Optional[str] = None
    company_name: Optional[str] = None
    organisation: Optional[bool] = None
    contact_person: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    address_line1: Optional[str] = None
    address_line2: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    postal_code: Optional[str] = None
    country: Optional[str] = None
    created_at: Optional[datetime.datetime] = None
    updated_at: Optional[datetime.datetime] = None
    is_deleted: bool
    deleted_at: Optional[datetime.datetime] = None


class User(pydantic.BaseModel):
    user_id: str
    sub: str
    email: str
    email_verified: Optional[bool] = None
    first_name: str
    last_name: str
    birthdate: Optional[datetime.date] = None
    created_date: datetime.datetime
    updated_at: datetime.datetime
    is_deleted: bool
    deleted_at: Optional[datetime.datetime] = None
