# Default value None added to Optional class members by fix.py
# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import datetime
import pydantic
from typing import Optional


class User(pydantic.BaseModel):
    user_id: str
    sub: str
    email: str
    email_verified: bool
    first_name: str
    last_name: str
    birthdate: Optional[datetime.date] = None
    created_date: datetime.datetime
    updated_at: datetime.datetime
    is_deleted: bool
    deleted_at: Optional[datetime.datetime] = None
