# Default value None added to Optional class members by fix.py
# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
# source: queries.sql
import datetime
import pydantic
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from repository import models


CREATE_USER = """-- name: create_user \\:one
INSERT INTO "user" (
    "sub",
    "email",
    "first_name",
    "last_name",
    "birthdate"
)
VALUES (
    :p1,
    :p2,
    :p3,
    :p4,
    :p5
) RETURNING user_id, sub, email, email_verified, first_name, last_name, birthdate, created_date, updated_at, is_deleted, deleted_at
"""


class CreateUserParams(pydantic.BaseModel):
    sub: str
    email: str
    first_name: str
    last_name: str
    birthdate: Optional[datetime.date] = None


GET_USER_BY_SUB = """-- name: get_user_by_sub \\:one
SELECT user_id, sub, email, email_verified, first_name, last_name, birthdate, created_date, updated_at, is_deleted, deleted_at FROM "user" WHERE "sub" = :p1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_user(self, arg: CreateUserParams) -> Optional[models.User]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_USER), {
            "p1": arg.sub,
            "p2": arg.email,
            "p3": arg.first_name,
            "p4": arg.last_name,
            "p5": arg.birthdate,
        })).first()
        if row is None:
            return None
        return models.User(
            user_id=row[0],
            sub=row[1],
            email=row[2],
            email_verified=row[3],
            first_name=row[4],
            last_name=row[5],
            birthdate=row[6],
            created_date=row[7],
            updated_at=row[8],
            is_deleted=row[9],
            deleted_at=row[10],
        )

    async def get_user_by_sub(self, *, sub: str) -> Optional[models.User]:
        row = (await self._conn.execute(sqlalchemy.text(GET_USER_BY_SUB), {"p1": sub})).first()
        if row is None:
            return None
        return models.User(
            user_id=row[0],
            sub=row[1],
            email=row[2],
            email_verified=row[3],
            first_name=row[4],
            last_name=row[5],
            birthdate=row[6],
            created_date=row[7],
            updated_at=row[8],
            is_deleted=row[9],
            deleted_at=row[10],
        )
