services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi-app:
    build:
      context: ../backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres-db:5432/service_app"
    depends_on:
      - postgres-db

volumes:
  postgres_data: